version: '3.8'

services:
  cinema:
    build: . #if we build the image directly from the dockerfile, otherwise use image: image-name
    container_name: cinema-container #name of the container we'll create
    ports: #specify ports if needed, overrides the EXPOSE from the dockerfile, i think
      - 100:90
    networks: #name of the network on which containers communicate
       net-cinema:
         ipv4_address: 10.5.0.18
    depends_on: #name of the db container this container depends on, means if the other service isn't launcher
      # this one won't be either
      - db-cinema

  db-cinema: #still a service, should be the same as the host from the app properties, "id" sorta
    image: mongo #name of the image to base this container on
    container_name: cinema-db #name of the container
    ports: #db ports, here, mongo's
      - 27017:27017
    volumes: #name of the docker volume that'll help in persisting data in case the containers crash
      - vol-cinema:/data/db #the second part depends on the database, not on the app
    networks: #name of the networks on which this container can communicate. it's an array
      net-cinema:
        ipv4_address: 10.5.0.4

networks: #declares the network(s)
  net-cinema:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1
volumes: #declares the volume(s)
  vol-cinema:
