name: Exercice Action
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "tests"
        run: echo "je fais les tests"
      - name: "build"
        run: echo "je fais le build"

