name: Exercice Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/develop'
    steps:
      - name: "tests"
        run: echo "je fais les tests"
      - name: "build"
        run: echo "je fais le build"

